server {
    listen 80;
    server_name pixorasoft.com www.pixorasoft.com;

    root /var/www/pixorasoft_maintenance;
    index maintenance.html;

    location / {
        try_files $uri $uri/ /maintenance.html;
    }
}
